name: Build & push Docker image
on:
  push:
    paths:
      - 'Dockerfile'
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t nmakamcbridge/sample_docker:`git rev-parse --short HEAD` .
      - name: Test
        run: docker run nmakamcbridge/sample_docker:`git rev-parse --short HEAD`
      - name: Push
        run: docker push nmakamcbridge/sample_docker:`git rev-parse --short HEAD`