name: Build & push Docker image
on:
  push:
    paths:
      - 'Dockerfile'
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Set sha_short
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Check outputs
        run: echo ${SHORT_SHA}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t nmakamcbridge/sample_docker:${SHORT_SHA} .
      - name: Test
        run: docker run nmakamcbridge/sample_docker:${SHORT_SHA}
      - name: Push
        run: docker push nmakamcbridge/sample_docker:${SHORT_SHA}