name: Build & push Docker image
on:
  push:
    paths:
      - 'Dockerfile'
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Set sha_short
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t nmakamcbridge/sample_docker:${{ steps.vars.outputs.sha_short }} .
      - name: Test
        run: docker run nmakamcbridge/sample_docker:${{ steps.vars.outputs.sha_short }}
      - name: Push
        run: docker push nmakamcbridge/sample_docker:${{ steps.vars.outputs.sha_short }}